### ISSUE TITLE
Supporting geotifs

### ISSUE THREAD

**Issue by robmarkcole** [bnsreenu/digitalsreeni-image-annotator#1]
Geotifs are commonly used in remote sensing. Simply by adding `imagecodecs` to the environment, they can be used. The app would benefit from tweaking the UI for this data, particularly for selecting the image dimensions, and then displaying RGB. I may have a go!

<img width="1389" alt="image" src="https://github.com/user-attachments/assets/a949f786-b045-45de-9a24-7ebf9a73308b">

**Comment by bnsreenu** [comment]
I haven't tested the application for Geotiffs. Thanks for the suggestion. I see that it already recognized the various channels in these files. I am afraid it may crash the application for very large files. Also, currently there is no concept of extracting patches from large images, just saving individual slices (channels) as whole images. Lot of room for improvement :)

**Comment by robmarkcole** [comment]
Do you think supporting both geospatial and microscopy is in the scope of this application, or would they be separate apps?

**Comment by bnsreenu** [comment]
I am aiming for application-agnostic interface. It is just annotation, not full segmentation application. Therefore, no need to add functionality of opening very large datasets. The user will not be able to finish annotation in one sitting so chunks of data can be opened at a time to continue annotation.

**Comment by robmarkcole** [comment]
With rasterio, you can read just the channels you need. I expect opening a sentinel 2 image, just RGB, should be fine. The workflow of annotating 1 large image in a sitting is also fine

**Comment by bnsreenu** [comment]
Closing this issue, since this is a new feature request. Thanks for the suggestion.

**Comment by bnsreenu** [comment]
Closing this issue, since this is a new feature request. Thanks for the suggestion.
