### ISSUE TITLE
DICOM support

### ISSUE THREAD

**Issue by orshaf** [bnsreenu/digitalsreeni-image-annotator#10]
Hi!
Does this tool support also DICOM format?

**Comment by bnsreenu** [comment]
Not yet. But I am considering a DICOM to tiff converter because you may be annotating 2D slices anyway. The program does not allow for 3D annotations. Does this work for you?

**Comment by orshaf** [comment]
Sounds great for future tasks :)
For now, I need 3d annotation for CT scans.
Thanks!

**Comment by bnsreenu** [comment]
This program does not support 3D annotations yet.

**Comment by bnsreenu** [comment]
Application not designed for 3D annotations.
