### ISSUE TITLE
Allow fine-tuning of the model after each completed picture

### ISSUE THREAD

**Issue by alpha-1-centauri** [bnsreenu/digitalsreeni-image-annotator#4]
I think it would be a really powerful tool if fine-tuning of the model was available on the go.
i.e. after each complete dphoto, the model was re-trained.

**Comment by bnsreenu** [comment]
Good idea. I was thinking of adding Mask R-CNN (Detectron2) to allow for custom-model based annotation assistance. I guess that functionality can be extended to do the actual training on the application and use the saved model to further enhance the annotation process.

**Comment by knoppmyth** [comment]
This really seems outside the scope of image annotator. Additionally, building a new model after each image seems like an inefficient use of time and compute.

**Comment by bnsreenu** [comment]
I have added the ability to train a YOLO model in version 0.7.x using the annotated data. This model can then be imported to predict images and the predictions can be accepted or rejected as annotations. While this may sound like a dream workflow, the actual process can be slow and not yielding good results as by definition you are annotating images to train a robust model. In any case, a YOLOv11 model can also be trained elsewhere and imported to predict.
