### ISSUE TITLE
Qt platform plugin issue in Linux

### ISSUE THREAD

**Issue by Jetliqs** [bnsreenu/digitalsreeni-image-annotator#5]
Hello, 
Thank you for the amazing tool, however, I have struggeled using it on my Ubuntu machine, I installed everything as described but I got the following error:

Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
QObject::moveToThread: Current thread (0x59d4e2bff9a0) is not the object's thread (0x59d4e9a67690).
Cannot move to target thread (0x59d4e2bff9a0)

qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/itougui/.virtualenvs/newpd/lib/python3.10/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, linuxfb, minimal, offscreen, vnc, webgl.

Aborted (core dumped)

I tried several solutions but I didn't succeed. Do you have any idea how to fix it?

Thanks

**Comment by bnsreenu** [comment]
This application is built using PyQt5 and has been tested on mac and Windows. Linux systems differ in how they handle Qt platform plugins. I hope someone can help in further optimizing the application for Linux, unfortunately I do not have access to a system, to test and optimize code for Linux.

**Comment by Jetliqs** [comment]
Thank you for your answer. Yes, I switched to Windows, and the application worked without problems. I have two suggestions, however: 
1. If I try to use a SAM model without picking one first, the application crashes and goes down, and everything I did before without manually saving is lost.
2. An "auto-save" feature in a future update will be great.

Thank you for the great tool.

**Comment by bnsreenu** [comment]
I am glad it works on Windows. 
1. It shouldn't let you click SAM unless you pick a model. Are you working with version 0.6.0?
2. auto-save is a good idea. Will add. Thanks.

**Comment by bnsreenu** [comment]
I fixed the SAM issue and also added AutoSave in v0.6.1 - now available. Thanks for your suggestions.

**Comment by bnsreenu** [comment]
Closing this issue since it got resolved. Although, the original issue of the application not working on Linux is acknowledged and updated system requirements to just mac and Windows.
