### ISSUE TITLE
[Feat] Add the ability to contract and expand polygons by x%

### ISSUE THREAD

**Issue by O-J1** [bnsreenu/digitalsreeni-image-annotator#8]
An issue I often come across every single time I use SAM or SAM2 in other tools is that it ends up being faster to manually annotate than fix the not usuable output it gives me. If I was able to increase the polygon by scaling it by x% (perhaps user set) then instead of SAM being completely unusable, it would become usable for these kinds of annotations.

For what its worth photoshop has a feature like this where you can expand and contract the mask but I obviously cant use PS for annotation haha.

![image](https://github.com/user-attachments/assets/216a17a8-e3c9-42f6-b8a9-0351ddbf6dd7)

**Comment by bnsreenu** [comment]
Expanding or contracting polygon annotations is not a universal solution to this problem. You can easily edit annotations to expand them. In fact, the latest version has paint brush tool to paint under-annotated regions and an eraser to do the opposite. These new (painted-in) annotations can be merged with others to form larger annotations. 

I will still include this feature request as part of my list and will consider when at least a couple others request a similar functionality. Thanks for sharing your request.

**Comment by O-J1** [comment]
> Expanding or contracting polygon annotations is not a universal solution to this problem. You can easily edit annotations to expand them. In fact, the latest version has paint brush tool to paint under-annotated regions and an eraser to do the opposite. These new (painted-in) annotations can be merged with others to form larger annotations.
> 
> I will still include this feature request as part of my list and will consider when at least a couple others request a similar functionality. Thanks for sharing your request.

🫡 Understood, the problem is time taken, like you said I can easily edit them, but it ends up being faster to just do it manually from the beginning (without SAM) which is why I wanted to at least try suggesting. Wish I knew of a better solution but alas.
