### ISSUE TITLE
Dataset Splitter

### ISSUE THREAD

**Issue by WoLogi** [bnsreenu/digitalsreeni-image-annotator#9]
Hi,

First of all, thanks for the great tool! I’ve been using the dataset splitter to handle my data, but I’ve encountered an issue that is making the process less efficient, and I’m not sure if I’m missing something or if this is a current limitation.

Currently, when I split a dataset, I can only load a COCO JSON file. However, my workflow requires me to export the output of the split in YOLO format. To do this, I have to perform many extra steps: first, load the COCO JSON, then split the dataset, and finally, load each split dataset again to export it in YOLO format.

It would be really helpful if the dataset splitter provided an option to choose the export format during the splitting process, allowing the user to select between COCO and YOLO formats directly. This would save a lot of time and effort.

Is there any way to achieve this more efficiently, or would it be possible to add this functionality in a future update?

Thank you for considering this, and I’m happy to provide more details or help in any way I can!

Best regards,

**Comment by bnsreenu** [comment]
I thought splitting YOLO is easy as each mage has its own corresponding label file. But I do understand that it adds a few manual steps. Let me add this request to my feature list, hopefully I should be able to include it in my next release. I will update here. Can you confirm the workflow? You want to load a YOLO yaml file with respective images and labels and split the data into train/val/test along with the labels. Is that correct?

**Comment by WoLogi** [comment]
That would be really nice. Not a yolo I mean a coco json. The point is I use SAM for annotation because its easier but in last step I need YOLO in split train/val/test with the corrosponding .txt files. At the Moment my workflow is I make annotation with coco then I split the dataset. After it I have 3 dictonary with coco json in test/val/train. Then I close my Project and load the annotation of test and Export it then again close and same with train and val. Hope its understandable since my english is not the best

**Comment by bnsreenu** [comment]
I am confused with so many terms being used. First of all, let us forget about SAM as it is just another tool to annotate. That leaves us with COCO and YOLO. Please answer my questions below so it makes it easy for communication:
1. What is the final format of annotations you want, is it COCO JSON or YOLO?
2. If it is YOLO, how do you want the final result? The standard format is a yaml file and train, val and test folders with each of them having images and labels directories.

**Comment by WoLogi** [comment]
sorry for that.
       1. The final format should be YOLO but import from COCO
       2. Thats right i need the data.yml train/val/test and the labels directories

**Comment by bnsreenu** [comment]
Closing this issue as I implemented the functionality in v0.8.2.
